### PR TITLE
Fix Leaking TraceViewerWidget instances

### LINKED ISSUE #730: Leaking TraceViewerWidget instances
At post-construction, the trace viewer widget adds a color theme change listener to the ThemeService and a Tsp client change listener to the Tsp client provider, but these listeners are not removed when the widget is disposed. This causes the trace viewer widget instance to leak.

### PR DESCRIPTION
**Pull request by hriday-panchasara**
Making use of toDispose.push in the Trace Viewer Widget to dispose its event listeners so that they
don't cause memory leaks

Fixes #730

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

### CODE REVIEW

File: theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx [hunk 1]
```diff
@@ -91,19 +91,22 @@ export class TraceViewerWidget extends ReactWidget implements StatefulWidget {
         this.title.closable = true;
         this.addClass('theia-trace-open');
         this.backgroundTheme = ThemeService.get().getCurrentTheme().type;
-        ThemeService.get().onDidColorThemeChange(() => this.updateBackgroundTheme());
+        this.toDispose.push(ThemeService.get().onDidColorThemeChange(() => this.updateBackgroundTheme()));
```
Comment (bhufmann) [inline theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx:94]: Since the upgrade to Theia 1.28, the API of the theme service has changed. This line needs to be:
`this.toDispose.push(this.themeService.onDidColorThemeChange(() => this.updateBackgroundTheme()));`

Please rebase this PR and update the PR.

**Review by bhufmann — CHANGES_REQUESTED** [review]

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Review by marco-miller — APPROVED** [review]
- LGTM too.
- Note, the commit message is lacking proper line wraps <=72 chars.
- Letting you merge at will, though (@bhufmann).
