### PR TITLE
table: Fix time sync. when searching previous and next

### LINKED ISSUE #743: Moving through filtered events in events table does not change selection in xy-chart / timeline-chart.
To replicate:
1) Open an XY Chart, a Timeline Chart, and an Events Table view.
2) Select an event in the Events Table.
3) Filter a column in the events table (use the spyglass icon).
4) While focused on the filter textbox, press enter to move to the next instance that meets search criteria.

Expected behavior: When you press enter / move to next search item, the blue selection marker moves on xy-chart and timeline-chart components.

166261536-eb1b10fd-b99c-4622-9447-390890f4900d

### PR DESCRIPTION
**Pull request by bhufmann**
fixes #743

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

File: packages/react-components/src/components/table-output-component.tsx [hunk 1]
```diff
@@ -609,6 +609,10 @@ export class TableOutputComponent extends AbstractOutputComponent<TableOutputPro
                 if (currRowIndexFound && !isFound && rowNode.data && rowNode.data['isMatched']) {
                     this.gridApi?.ensureIndexVisible(rowNode.rowIndex);
                     this.selectStartIndex = this.selectEndIndex = rowNode.rowIndex;
+                    if (this.timestampCol) {
+                        this.startTimestamp = BigInt(rowNode.data[this.timestampCol]);
+                        this.endTimestamp = BigInt(rowNode.data[this.timestampCol]);
+                    }
```
Comment (PatrickTasse) [inline packages/react-components/src/components/table-output-component.tsx:615]: It only works if the match is found in the current cache. Otherwise it find the index below and ensures it's made visible. We probably need for the lines to be loaded before we can update the selected time and fire the selection changed signal.

**Review by PatrickTasse — CHANGES_REQUESTED** [review]

File: packages/react-components/src/components/table-output-component.tsx (hunk 1 above)
Comment (bhufmann) [reply packages/react-components/src/components/table-output-component.tsx:616]: Thanks for finding this.

**Review by PatrickTasse — APPROVED** [review]
