### PR TITLE
TableOutputComponent: Fix these search selection related cases

### LINKED ISSUE #859: Hitting Enter right after entering a search filter doesn't select the first entry in table(s)
1. Run trace-server.
2. Provision it with a trace or an experiment.
3. Run extension's `yarn start:browser`.
4. Browse to `http://localhost:3000/`.
5. Open the provisioned trace from the Trace Viewer.
6. Select the Events (or any other) Table for that trace.
7. Enter a Search filter in any one of the table columns.
8. Hit Enter right after entering the few filter characters.
9. Notice the wrong (non-first filtered) table entry being selected.

### PR DESCRIPTION
**Pull request by marco-miller**
This PR is made of these commits with more details in their respective commit messages:

1. Fix findMatchedEvent row 0 case.
2. Fix backward search upon index 0.
3. Fix selectStartIndex assigned to itself.
4. Wait for search before selecting.
5. Fix exception upon early Enter.
6. Reset navigating selection if new search.
7. Separate search and matching.
8. **Decrease debounce ms by 50x.**

**The latter (PR's head) commit** formally fixes #859.

Signed-off-by: Marco Miller <marco.miller@ericsson.com>

### CODE REVIEW

File: packages/react-components/src/components/table-output-component.tsx [hunk 1]
```diff
@@ -626,13 +639,28 @@ export class TableOutputComponent extends AbstractOutputComponent<TableOutputPro
...
         if (this.gridApi) {
+            const msBetweenChecks = 100;
+            while (this.gridMatched) {
+                // wait for grid to be done being matched -from elsewhere (concurrently)
+                await new Promise(cb => setTimeout(cb, msBetweenChecks));
+            }
+            while (this.gridRedrawn) {
+                // wait for grid to be done being redrawn -elsewhere (before assuming it)
+                await new Promise(cb => setTimeout(cb, msBetweenChecks));
+            }
```
Comment (Rodrigoplp-work) [inline packages/react-components/src/components/table-output-component.tsx:650]: I couldn't trigger these awaits. I'm afraid they are never called.

File: packages/react-components/src/components/table-output-component.tsx [hunk 2]
```diff
@@ -603,6 +614,8 @@ export class TableOutputComponent extends AbstractOutputComponent<TableOutputPro
             });
             this.gridApi.redrawRows();
         }
+        this.gridSearched = true;
+        this.gridRedrawn = false;
```
Comment (Rodrigoplp-work) [inline packages/react-components/src/components/table-output-component.tsx:618]: Good thinking, but doesn't seem to be enough. The problem is that `searchEvents` is triggered by `gridApi` every time a character is typed, but it changes the nodes on each pass, which delays the following triggers and changes. This makes it unreliable to control the `gridRedrawn` flag.
Maybe if we stop changing the nodes with `rowNode.data['isMatched'] = isMatched;`, and control the matched rows with a new independent array, then searchEvents would become fast enough to allow using `gridRedrawn` here.

File: packages/react-components/src/components/table-output-component.tsx [hunk 3]
```diff
@@ -674,7 +708,8 @@ export class TableOutputComponent extends AbstractOutputComponent<TableOutputPro
                     // non-contiguous row found, stop searching in cache
                     currRowIndexFound = false;
                 }
-                if (currRowIndexFound && !isFound && rowNode.rowIndex && rowNode.data && rowNode.data['isMatched']) {
+                // only checking 'rowNode.rowIndex' below makes its '=== 0' case false:
+                if (currRowIndexFound && !isFound && (rowNode.rowIndex || rowNode.rowIndex === 0) && rowNode.data && rowNode.data['isMatched']) {
```
Comment (Rodrigoplp-work) [inline packages/react-components/src/components/table-output-component.tsx:712]: Still, `rowNode.data.isMatched` is giving false positives due to the issue with `searchEvents`.

**Review by Rodrigoplp-work — CHANGES_REQUESTED** [review]
Clever attempt! It reduced the number of failures when pressing enter in a search field. But it still happens if I'm fast enough. I believe we have a problem in `searchEvents` which may require a better way to control matches.

File: packages/react-components/src/components/table-output-component.tsx (hunk 1 above)
Comment (marco-miller) [reply packages/react-components/src/components/table-output-component.tsx:650]: I propose to keep this in as (small) safety, until we can work on the more major refactoring you proposed.

File: packages/react-components/src/components/table-output-component.tsx (hunk 2 above)
Comment (marco-miller) [reply packages/react-components/src/components/table-output-component.tsx:618]: I think we should keep this promising yet major refactoring for another iteration or PR. It may unveil more issues while fixing the design at a broader scope.

File: packages/react-components/src/components/table-output-component.tsx (hunk 3 above)
Comment (marco-miller) [reply packages/react-components/src/components/table-output-component.tsx:712]: I understand, however this fix remains necessary within its smaller scope, I think.

**Comment by marco-miller** [comment]
> Clever attempt! It reduced the number of failures when pressing enter in a search field. But it still happens if I'm fast enough. I believe we have a problem in `searchEvents` which may require a better way to control matches.

I reduced the debounce timeout to 5x smaller in the head commit. I wasn't able to be faster than that locally. Can you retest using this latest value, please? I hesitated in putting 0 in there, so I thought of 10 as the smallest sensible value.

**Comment by Rodrigoplp-work** [comment]
> > Clever attempt! It reduced the number of failures when pressing enter in a search field. But it still happens if I'm fast enough. I believe we have a problem in `searchEvents` which may require a better way to control matches.
> 
> I reduced the debounce timeout to 5x smaller in the head commit. I wasn't able to be faster than that locally. Can you retest using this latest value, please? I hesitated in putting 0 in there, so I thought of 10 as the smallest sensible value.

`0` doesn't solve the problem, so I agree with `10`.
I also agree with merging this because of the improvements it brings, and trying to work more on this in the future.
To that goal I suggest removing the comment "fixes #859" from the commits, so that we keep it open to track the issue.

**Comment by marco-miller** [comment]
> `0` doesn't solve the problem, so I agree with `10`. I also agree with merging this because of the improvements it brings, and trying to work more on this in the future. To that goal I suggest removing the comment "fixes #859" from the commits, so that we keep it open to track the issue.

Thanks. I amended the top commit message accordingly.

**Review by Rodrigoplp-work — APPROVED** [review]
